In [38]:
import pandas as pd
import numpy as np

In [175]:
#CHECK CLEAN, only 264 rows!
start_date = pd.to_datetime('2001-01-01')
end_date = pd.to_datetime('2022-12-31')
pd.read_csv("../clean_data/resp/clean_ph.csv")

,Unnamed: 0,California,Texas,North Dakota,Wyoming,Pennsylvania,West Virginia,Oklahoma,Florida,New York,Ohio
0,2001-01-01,7.930108,7.472331,7.571774,8.180000,6.047379,7.243333,7.739113,7.780000,8.007246,7.450682
1,2001-02-01,8.039286,7.511366,7.525000,8.180000,5.895461,7.243333,7.650000,7.780000,8.007246,7.390995
2,2001-03-01,8.144086,7.439437,7.608065,8.180000,6.939857,7.243333,7.556290,7.735714,8.007246,7.660789
3,2001-04-01,8.012556,7.541860,8.214167,8.154348,6.968819,7.243333,7.827917,7.650000,8.007246,7.485656
4,2001-05-01,7.953763,7.648075,8.337097,7.686111,6.922132,7.243333,7.588817,7.953333,8.007246,7.387821
...,...,...,...,...,...,...,...,...,...,...,...
259,2022-08-01,7.898180,7.975502,8.296989,8.061290,7.707585,7.796911,8.149977,7.319975,7.756573,7.938600
260,2022-09-01,7.854580,7.965684,8.402667,7.995833,7.730803,7.846245,7.953333,7.242145,7.803483,7.910273
261,2022-10-01,7.837428,8.050167,8.480072,8.093000,7.755555,7.825817,7.997034,7.392603,7.914533,7.994524
262,2022-11-01,7.927999,7.819498,8.557778,8.093000,7.667910,7.726117,7.898194,7.469025,7.903684,7.983438
263,2022-12-01,7.817978,7.734603,8.281004,8.093000,7.604371,7.674068,7.860816,7.487747,7.928020,8.119821

In [49]:
turb = pd.read_csv("Water/turbidity_monthly.csv").set_index("datetimeUTC")
turb.index = pd.to_datetime(turb.index)
turbnonna = turb.fillna(method="bfill").fillna(method="ffill") #interpolate
# turbnonna.to_csv("Water/turbidity_monthly_nonna.csv")
producers = {"Texas", "North Dakota", "Wyoming", "Pennsylvania", "Oklahoma", "West Virginia"}
consumers = {"Texas", "California", "New York", "Florida", "Ohio", "Pennsylvania"}
relevstates = list(producers.union(consumers))
usstates = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

In [3]:
ph = pd.read_csv("Water/pH_monthly.csv").set_index("datetimeUTC")
ph.index = pd.to_datetime(ph.index)
ph = ph.fillna(method="bfill").fillna(method="ffill") #interpolate
ph

,California,Texas,North Dakota,Wyoming,Pennsylvania,West Virginia,Oklahoma,Florida,New York,Ohio
datetimeUTC,,,,,,,,,,
2000-01-31 00:00:00+00:00,8.317204,7.569588,7.641935,8.180000,6.270027,7.243333,7.820645,7.780000,8.007246,7.318536
2000-02-29 00:00:00+00:00,8.116379,7.588297,7.647321,8.180000,6.217853,7.243333,7.863448,7.780000,8.007246,7.383687
2000-03-31 00:00:00+00:00,8.110941,7.687039,8.077500,8.180000,6.352823,7.243333,7.634839,7.780000,8.007246,7.008531
2000-04-30 00:00:00+00:00,7.831667,7.673864,8.320833,8.180000,6.622318,7.243333,7.812667,7.780000,8.007246,7.169826
2000-05-31 00:00:00+00:00,7.815430,7.569981,8.372581,8.180000,6.770357,7.243333,7.461505,7.780000,8.007246,7.275332
...,...,...,...,...,...,...,...,...,...,...
2022-08-31 00:00:00+00:00,7.898180,7.975502,8.296989,8.061290,7.707585,7.796911,8.149977,7.319975,7.756573,7.938600
2022-09-30 00:00:00+00:00,7.854580,7.965684,8.402667,7.995833,7.730803,7.846245,7.953333,7.242145,7.803483,7.910273
2022-10-31 00:00:00+00:00,7.837428,8.050167,8.480072,8.093000,7.755555,7.825817,7.997034,7.392603,7.914533,7.994524
2022-11-30 00:00:00+00:00,7.927999,7.819498,8.557778,8.093000,7.667910,7.726117,7.898194,7.469025,7.903684,7.983438
2022-12-31 00:00:00+00:00,7.817978,7.734603,8.281004,8.093000,7.604371,7.674068,7.860816,7.487747,7.928020,8.119821

In [4]:
temp = pd.read_csv("Water/temperature_monthly.csv").set_index("datetimeUTC")
temp.index = pd.to_datetime(temp.index)
temp = temp.fillna(method="bfill").fillna(method="ffill") #interpolate
temp.resample("MS").mean()

,California,Texas,North Dakota,Wyoming,Pennsylvania,West Virginia,Oklahoma,Florida,New York,Ohio
datetimeUTC,,,,,,,,,,
2000-01-01 00:00:00+00:00,9.178916,12.445836,0.783656,0.045161,2.368902,2.491935,5.682437,19.011127,1.201868,3.340598
2000-02-01 00:00:00+00:00,9.914265,15.157896,1.332989,0.405747,2.267108,3.750000,8.703448,19.756983,0.846331,4.119287
2000-03-01 00:00:00+00:00,11.156489,18.204863,3.457043,3.229032,6.821660,8.145161,12.275986,23.263321,4.431051,9.965557
2000-04-01 00:00:00+00:00,13.570469,20.714020,8.685681,9.367778,10.050706,11.125000,16.698148,24.153959,7.774637,12.320933
2000-05-01 00:00:00+00:00,15.317995,25.044272,15.998694,11.838710,15.322927,15.491935,20.693369,27.407253,13.506535,19.024503
...,...,...,...,...,...,...,...,...,...,...
2022-08-01 00:00:00+00:00,19.537764,28.551445,22.939558,18.675138,22.691034,22.322228,26.514215,28.547353,20.875112,22.957689
2022-09-01 00:00:00+00:00,18.180644,27.057506,17.880304,15.548521,19.345940,19.965941,24.276610,27.196034,17.867870,19.880930
2022-10-01 00:00:00+00:00,15.170036,22.548581,9.400869,10.417843,12.494275,12.276018,18.497588,24.061891,12.220596,12.216695
2022-11-01 00:00:00+00:00,9.512101,17.693974,1.902397,5.557778,8.596683,8.784340,12.625269,22.843775,8.295794,7.969582
2022-12-01 00:00:00+00:00,8.116427,15.133223,0.200498,4.982788,3.628426,4.149342,8.460218,20.078833,3.352556,3.345580

In [150]:
net_rev = pd.read_csv("../raw_data/revenue.csv")
rev_df = net_rev.iloc[3:, :].set_index("Revenue from retail sales of electricity")
rev_df.columns = rev_df.iloc[0, :].values
rev_df = rev_df.iloc[:, 2:]
rev_df[rev_df=="--"] = np.nan
rev_df[rev_df=="NM"] = np.nan
rev_df = rev_df.dropna().iloc[1:,:].astype(float)
stateindall = pd.Series(rev_df.index).str.extract("(.*) : .*").rename(columns={0:"State"})
matching = np.where(pd.Series(rev_df.index).str.match(".* : all sectors"))[0]
rev_df = pd.concat([rev_df.reset_index().iloc[matching, :], stateindall.loc[matching]], axis=1).iloc[:,1:]
rev_df = rev_df.set_index("State").T.loc[:, relevstates]
start_date = pd.to_datetime('2001-01-01')
end_date = pd.to_datetime('2022-12-31')
mos = pd.date_range(start=start_date, end=end_date, freq='MS')
rev_df.index = mos
rev_df

State,Oklahoma,Wyoming,California,West Virginia,New York,North Dakota,Texas,Pennsylvania,Ohio,Florida
2001-01-01,255.0,48.0,1893.0,148.0,1470.0,48.0,1904.0,976.0,922.0,1366.0
2001-02-01,211.0,49.0,1762.0,120.0,1343.0,48.0,1671.0,884.0,842.0,1142.0
2001-03-01,217.0,48.0,2111.0,124.0,1299.0,44.0,1575.0,891.0,848.0,1080.0
2001-04-01,209.0,45.0,1862.0,112.0,1178.0,40.0,1593.0,824.0,771.0,1152.0
2001-05-01,239.0,45.0,1950.0,106.0,1208.0,41.0,1800.0,823.0,841.0,1184.0
...,...,...,...,...,...,...,...,...,...,...
2022-08-01,855.0,120.0,6781.0,287.0,2854.0,183.0,5190.0,1764.0,1665.0,3454.0
2022-09-01,685.0,110.0,6303.0,240.0,2630.0,174.0,4588.0,1506.0,1379.0,3184.0
2022-10-01,536.0,108.0,4903.0,248.0,2036.0,175.0,3725.0,1298.0,1227.0,2636.0
2022-11-01,488.0,116.0,4025.0,272.0,1905.0,186.0,3261.0,1329.0,1257.0,2400.0
2022-12-01,541.0,128.0,4249.0,312.0,2179.0,189.0,3641.0,1732.0,1418.0,2506.0

In [154]:
sum(np.ravel(~rev_df.isna().values)) == rev_df.shape[0]*rev_df.shape[1]

True

In [88]:
pd.concat([rev_df, stateindall], axis=1)

,Revenue from retail sales of electricity,Jan 2001,Feb 2001,Mar 2001,Apr 2001,May 2001,Jun 2001,Jul 2001,Aug 2001,Sep 2001,...,Apr 2022,May 2022,Jun 2022,Jul 2022,Aug 2022,Sep 2022,Oct 2022,Nov 2022,Dec 2022,0
0,United States : all sectors,20978.0,18700.0,18880.0,17856.0,18970.0,21977.0,24876.0,26037.0,22564.0,...,33254.0,37332.0,44620.0,51394.0,52691.0,45670.0,37817.0,36123.0,40776.0,United States
1,United States : residential,9827.0,8030.0,7721.0,6974.0,7217.0,9014.0,10901.0,11645.0,9454.0,...,14446.0,16625.0,21172.0,25536.0,25758.0,21269.0,16125.0,16256.0,19889.0,United States
2,United States : commercial,6587.0,6119.0,6470.0,6269.0,6794.0,7779.0,8592.0,8816.0,7949.0,...,12384.0,13528.0,15483.0,17395.0,18157.0,16480.0,14394.0,13124.0,13881.0,United States
3,United States : industrial,3952.0,3945.0,4061.0,4006.0,4303.0,4458.0,4631.0,4775.0,4392.0,...,6367.0,7121.0,7903.0,8392.0,8708.0,7852.0,7234.0,6680.0,6937.0,United States
4,New England : all sectors,1140.0,1006.0,1079.0,966.0,989.0,1126.0,1217.0,1182.0,1080.0,...,1719.0,1684.0,1819.0,2100.0,2457.0,2095.0,1742.0,1771.0,2120.0,New England
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,Alaska : industrial,6.0,6.0,7.0,7.0,6.0,7.0,7.0,8.0,6.0,...,21.0,23.0,22.0,22.0,20.0,18.0,22.0,20.0,21.0,Alaska
241,Hawaii : all sectors,119.0,104.0,114.0,108.0,114.0,113.0,123.0,126.0,120.0,...,270.0,297.0,299.0,326.0,339.0,338.0,342.0,310.0,315.0,Hawaii
242,Hawaii : residential,42.0,34.0,38.0,36.0,37.0,37.0,41.0,41.0,39.0,...,89.0,97.0,100.0,107.0,112.0,110.0,111.0,100.0,103.0,Hawaii
243,Hawaii : commercial,38.0,35.0,38.0,36.0,39.0,38.0,41.0,42.0,41.0,...,87.0,96.0,95.0,103.0,108.0,108.0,109.0,99.0,98.0,Hawaii
244,Hawaii : industrial,38.0,34.0,37.0,35.0,37.0,37.0,40.0,42.0,38.0,...,95.0,104.0,104.0,117.0,119.0,120.0,122.0,112.0,113.0,Hawaii

In [60]:
rev_df.iloc[ind, :]

,Jan 2001,Feb 2001,Mar 2001,Apr 2001,May 2001,Jun 2001,Jul 2001,Aug 2001,Sep 2001,Oct 2001,...,Mar 2022,Apr 2022,May 2022,Jun 2022,Jul 2022,Aug 2022,Sep 2022,Oct 2022,Nov 2022,Dec 2022
Revenue from retail sales of electricity,,,,,,,,,,,,,,,,,,,,,
Connecticut : all sectors,269.0,221.0,242.0,215.0,226.0,254.0,262.0,296.0,233.0,230.0,...,454.0,426.0,432.0,489.0,516.0,656.0,500.0,413.0,416.0,503.0
Maine : all sectors,119.0,111.0,109.0,94.0,94.0,103.0,109.0,119.0,102.0,103.0,...,198.0,174.0,168.0,164.0,169.0,187.0,169.0,144.0,152.0,178.0
Massachusetts : all sectors,508.0,459.0,501.0,453.0,469.0,550.0,616.0,526.0,546.0,504.0,...,861.0,783.0,753.0,828.0,996.0,1131.0,1015.0,830.0,826.0,985.0
New Hampshire : all sectors,115.0,95.0,101.0,93.0,84.0,93.0,99.0,102.0,83.0,90.0,...,176.0,153.0,157.0,165.0,199.0,246.0,215.0,177.0,187.0,231.0
Rhode Island : all sectors,72.0,67.0,74.0,67.0,70.0,77.0,79.0,85.0,67.0,64.0,...,120.0,114.0,102.0,100.0,136.0,149.0,124.0,107.0,116.0,137.0
Vermont : all sectors,57.0,53.0,51.0,45.0,46.0,49.0,52.0,55.0,49.0,49.0,...,79.0,70.0,72.0,74.0,84.0,87.0,74.0,72.0,74.0,85.0
New Jersey : all sectors,571.0,497.0,524.0,495.0,511.0,637.0,699.0,754.0,622.0,528.0,...,808.0,729.0,845.0,1017.0,1323.0,1328.0,910.0,733.0,727.0,898.0
New York : all sectors,1470.0,1343.0,1299.0,1178.0,1208.0,1398.0,1664.0,1735.0,1564.0,1330.0,...,1908.0,1764.0,1810.0,2253.0,2683.0,2854.0,2630.0,2036.0,1905.0,2179.0
Pennsylvania : all sectors,976.0,884.0,891.0,824.0,823.0,938.0,984.0,1059.0,916.0,835.0,...,1258.0,1169.0,1194.0,1442.0,1705.0,1764.0,1506.0,1298.0,1329.0,1732.0
Illinois : all sectors,727.0,721.0,693.0,636.0,737.0,859.0,1008.0,1081.0,832.0,712.0,...,1208.0,1119.0,1317.0,1610.0,1782.0,1760.0,1486.0,1216.0,1229.0,1446.0
Indiana : all sectors,457.0,408.0,410.0,386.0,402.0,446.0,495.0,514.0,433.0,419.0,...,895.0,835.0,925.0,1059.0,1168.0,1251.0,986.0,955.0,947.0,1078.0
Michigan : all sectors,622.0,548.0,591.0,521.0,557.0,633.0,694.0,743.0,563.0,558.0,...,1033.0,960.0,1045.0,1196.0,1330.0,1298.0,1075.0,980.0,981.0,1142.0
Ohio : all sectors,922.0,842.0,848.0,771.0,841.0,880.0,1003.0,1039.0,828.0,809.0,...,1229.0,1120.0,1227.0,1473.0,1684.0,1665.0,1379.0,1227.0,1257.0,1418.0
Wisconsin : all sectors,336.0,313.0,318.0,295.0,311.0,336.0,385.0,400.0,324.0,315.0,...,659.0,596.0,658.0,746.0,807.0,798.0,707.0,618.0,628.0,698.0
Iowa : all sectors,195.0,180.0,178.0,181.0,196.0,217.0,267.0,270.0,197.0,181.0,...,368.0,343.0,417.0,522.0,604.0,571.0,462.0,358.0,368.0,406.0
Kansas : all sectors,172.0,156.0,164.0,156.0,174.0,207.0,279.0,269.0,196.0,164.0,...,337.0,324.0,378.0,472.0,554.0,559.0,466.0,380.0,362.0,384.0
Minnesota : all sectors,295.0,280.0,275.0,253.0,283.0,327.0,395.0,414.0,291.0,264.0,...,641.0,577.0,612.0,709.0,792.0,771.0,691.0,603.0,607.0,664.0
Missouri : all sectors,365.0,320.0,310.0,293.0,346.0,432.0,546.0,531.0,374.0,296.0,...,586.0,537.0,606.0,876.0,1030.0,1011.0,793.0,558.0,601.0,695.0
Nebraska : all sectors,102.0,99.0,97.0,90.0,97.0,122.0,154.0,151.0,126.0,100.0,...,227.0,207.0,223.0,270.0,313.0,320.0,263.0,218.0,217.0,248.0
North Dakota : all sectors,48.0,48.0,44.0,40.0,41.0,42.0,49.0,50.0,45.0,43.0,...,180.0,158.0,162.0,172.0,180.0,183.0,174.0,175.0,186.0,189.0
South Dakota : all sectors,47.0,46.0,43.0,41.0,41.0,45.0,55.0,58.0,47.0,41.0,...,115.0,108.0,103.0,116.0,133.0,135.0,116.0,106.0,109.0,125.0
Delaware : all sectors,65.0,57.0,61.0,55.0,55.0,65.0,81.0,83.0,79.0,60.0,...,104.0,94.0,100.0,113.0,139.0,147.0,124.0,105.0,102.0,130.0
Florida : all sectors,1366.0,1142.0,1080.0,1152.0,1184.0,1311.0,1504.0,1531.0,1571.0,1271.0,...,2361.0,2353.0,2712.0,3080.0,3386.0,3454.0,3184.0,2636.0,2400.0,2506.0
Georgia : all sectors,648.0,553.0,540.0,538.0,587.0,701.0,816.0,874.0,677.0,569.0,...,1126.0,1122.0,1468.0,1978.0,2190.0,2090.0,1639.0,1253.0,1216.0,1295.0
Maryland : all sectors,351.0,301.0,318.0,281.0,317.0,390.0,421.0,469.0,371.0,284.0,...,582.0,507.0,566.0,679.0,802.0,793.0,636.0,593.0,611.0,805.0
North Carolina : all sectors,740.0,625.0,592.0,584.0,571.0,663.0,759.0,799.0,780.0,583.0,...,1021.0,912.0,1121.0,1239.0,1440.0,1441.0,1218.0,1051.0,1035.0,1259.0
South Carolina : all sectors,429.0,354.0,317.0,319.0,319.0,372.0,416.0,440.0,388.0,354.0,...,633.0,587.0,749.0,883.0,1023.0,985.0,842.0,658.0,683.0,819.0
Virginia : all sectors,561.0,471.0,489.0,433.0,446.0,535.0,570.0,618.0,482.0,444.0,...,930.0,935.0,1050.0,1140.0,1476.0,1415.0,1227.0,1081.0,1159.0,1363.0
West Virginia : all sectors,148.0,120.0,124.0,112.0,106.0,108.0,117.0,122.0,108.0,111.0,...,261.0,229.0,247.0,262.0,289.0,287.0,240.0,248.0,272.0,312.0
Alabama : all sectors,408.0,321.0,346.0,347.0,359.0,399.0,453.0,457.0,395.0,329.0,...,684.0,674.0,825.0,1026.0,1142.0,1139.0,956.0,751.0,765.0,794.0
Kentucky : all sectors,315.0,267.0,277.0,258.0,259.0,282.0,317.0,335.0,289.0,259.0,...,569.0,555.0,615.0,741.0,825.0,808.0,677.0,578.0,597.0,690.0
Mississippi : all sectors,234.0,197.0,188.0,199.0,222.0,258.0,295.0,312.0,284.0,210.0,...,386.0,364.0,414.0,495.0,539.0,544.0,505.0,430.0,392.0,413.0
Tennessee : all sectors,539.0,460.0,406.0,409.0,405.0,436.0,490.0,519.0,498.0,398.0,...,794.0,755.0,797.0,998.0,1259.0,1298.0,1055.0,834.0,804.0,904.0
Arkansas : all sectors,217.0,182.0,174.0,180.0,189.0,232.0,270.0,291.0,262.0,190.0,...,339.0,318.0,365.0,451.0,558.0,538.0,468.0,377.0,342.0,382.0
Louisiana : all sectors,484.0,459.0,458.0,424.0,441.0,525.0,494.0,480.0,450.0,406.0,...,614.0,619.0,723.0,949.0,1116.0,1070.0,970.0,876.0,777.0,768.0
Oklahoma : all sectors,255.0,211.0,217.0,209.0,239.0,309.0,384.0,398.0,273.0,192.0,...,432.0,415.0,546.0,702.0,849.0,855.0,685.0,536.0,488.0,541.0
Texas : all sectors,1904.0,1671.0,1575.0,1593.0,1800.0,2253.0,2515.0,2708.0,2428.0,1885.0,...,3215.0,3071.0,3827.0,4541.0,5138.0,5190.0,4588.0,3725.0,3261.0,3641.0
Arizona : all sectors,304.0,286.0,287.0,288.0,403.0,466.0,504.0,514.0,476.0,412.0,...,576.0,640.0,816.0,1027.0,1167.0,1105.0,984.0,724.0,587.0,667.0
Colorado : all sectors,215.0,198.0,199.0,193.0,214.0,239.0,250.0,248.0,265.0,229.0,...,508.0,475.0,494.0,604.0,718.0,727.0,622.0,534.0,531.0,576.0
Idaho : all sectors,90.0,78.0,74.0,69.0,87.0,93.0,97.0,104.0,79.0,80.0,...,157.0,149.0,159.0,206.0,260.0,238.0,178.0,153.0,170.0,202.0
Montana : all sectors,63.0,72.0,66.0,64.0,61.0,63.0,60.0,63.0,58.0,54.0,...,119.0,118.0,110.0,105.0,119.0,146.0,132.0,114.0,136.0,192.0
Nevada : all sectors,138.0,121.0,146.0,163.0,191.0,221.0,250.0,257.0,232.0,177.0,...,248.0,272.0,324.0,425.0,534.0,482.0,488.0,350.0,311.0,366.0
New Mexico : all sectors,111.0,103.0,102.0,96.0,109.0,118.0,130.0,130.0,124.0,113.0,...,199.0,194.0,207.0,257.0,307.0,292.0,271.0,232.0,220.0,219.0
Utah : all sectors,95.0,95.0,89.0,89.0,103.0,107.0,120.0,119.0,103.0,100.0,...,210.0,198.0,214.0,264.0,336.0,310.0,282.0,225.0,225.0,249.0
Wyoming : all sectors,48.0,49.0,48.0,45.0,45.0,45.0,48.0,52.0,48.0,48.0,...,115.0,108.0,107.0,107.0,120.0,120.0,110.0,108.0,116.0,128.0
California : all sectors,1893.0,1762.0,2111.0,1862.0,1950.0,2404.0,2900.0,3120.0,2705.0,2752.0,...,4109.0,3811.0,4074.0,5112.0,5833.0,6781.0,6303.0,4903.0,4025.0,4249.0
Oregon : all sectors,243.0,224.0,220.0,201.0,193.0,184.0,177.0,185.0,174.0,195.0,...,400.0,386.0,371.0,365.0,429.0,443.0,379.0,376.0,438.0,496.0
Washington : all sectors,441.0,425.0,395.0,364.0,342.0,301.0,287.0,291.0,285.0,312.0,...,722.0,661.0,608.0,586.0,628.0,679.0,611.0,593.0,701.0,832.0
Hawaii : all sectors,119.0,104.0,114.0,108.0,114.0,113.0,123.0,126.0,120.0,117.0,...,266.0,270.0,297.0,299.0,326.0,339.0,338.0,342.0,310.0,315.0